application: goagent
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_gh/.*
  script: gae.application
  secure: optional

- url: /favicon.ico
  script: gae.application
  secure: optional

- url: /2.*
  script: legacy.application
  secure: optional

- url: /fetch\.py
  script: legacy.LegacyHandler.application
  secure: optional

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

libraries:
- name: pycrypto
  version: "latest"
